// Font sizes here are BASE sizes (at 1280px video width).
// CaptionRenderer scales them proportionally to actual video container width.
// Rule of thumb: target ~3.5% of video width in pixels.

export const CAPTION_STYLES = {
  highlight: {
    id: 'highlight',
    name: '✨ Word Highlight',
    description: 'Active word pops with color — viral shorts style',
    fontFamily: 'Poppins',
    fontSize: 28,            // base px — renderer scales to container
    color: '#FFFFFF',
    highlightColor: '#38BDF8',
    backgroundColor: 'rgba(0,0,0,0.55)',
    position: 'bottom',
    verticalOffset: 10,
    textAlign: 'center',
    textTransform: 'uppercase',
    animation: 'pop',
    boxPadding: 10,
    boxRadius: 12,
    textShadow: '0 2px 10px rgba(0,0,0,0.9)',
    fontWeight: '800',
    letterSpacing: '0.02em',
    strokeColor: null,
    strokeWidth: 0,
  },
  bold: {
    id: 'bold',
    name: '🔥 Bold Punch',
    description: 'Thick uppercase impact text with heavy shadow',
    fontFamily: 'Outfit',
    fontSize: 30,
    color: '#FFFFFF',
    highlightColor: '#FACC15',
    backgroundColor: 'transparent',
    position: 'bottom',
    verticalOffset: 10,
    textAlign: 'center',
    textTransform: 'uppercase',
    animation: 'pop',
    boxPadding: 6,
    boxRadius: 6,
    textShadow: '0 3px 14px rgba(0,0,0,0.98), 0 0 6px #000',
    fontWeight: '900',
    letterSpacing: '0.04em',
    strokeColor: '#000000',
    strokeWidth: 3,
  },
  tiktok: {
    id: 'tiktok',
    name: '🎵 TikTok Viral',
    description: 'Bright yellow highlight word on dark pill — proven viral format',
    fontFamily: 'Montserrat',
    fontSize: 26,
    color: '#FFFFFF',
    highlightColor: '#FACC15',
    backgroundColor: 'rgba(0,0,0,0.8)',
    position: 'bottom',
    verticalOffset: 8,
    textAlign: 'center',
    textTransform: 'uppercase',
    animation: 'pop',
    boxPadding: 12,
    boxRadius: 8,
    textShadow: 'none',
    fontWeight: '900',
    letterSpacing: '0.03em',
    strokeColor: null,
    strokeWidth: 0,
  },
  box: {
    id: 'box',
    name: '⬛ Rounded Box',
    description: 'Semi-transparent pill container around each caption',
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 24,
    color: '#FFFFFF',
    highlightColor: '#4ADE80',
    backgroundColor: 'rgba(15,23,42,0.85)',
    position: 'bottom',
    verticalOffset: 10,
    textAlign: 'center',
    textTransform: 'none',
    animation: 'bounce',
    boxPadding: 14,
    boxRadius: 999,            // pill shape
    textShadow: 'none',
    fontWeight: '700',
    letterSpacing: '0.01em',
    strokeColor: null,
    strokeWidth: 0,
  },
  glow: {
    id: 'glow',
    name: '💜 Neon Glow',
    description: 'Glowing neon word on dark background — cinematic look',
    fontFamily: 'Montserrat',
    fontSize: 27,
    color: '#F1F5F9',
    highlightColor: '#A855F7',
    backgroundColor: 'rgba(5,5,15,0.72)',
    position: 'bottom',
    verticalOffset: 10,
    textAlign: 'center',
    textTransform: 'uppercase',
    animation: 'pop',
    boxPadding: 10,
    boxRadius: 12,
    textShadow: '0 0 18px rgba(168,85,247,0.7), 0 2px 8px rgba(0,0,0,0.9)',
    fontWeight: '900',
    letterSpacing: '0.04em',
    strokeColor: null,
    strokeWidth: 0,
  },
  clean: {
    id: 'clean',
    name: '🤍 Clean Minimal',
    description: 'Simple white text with shadow — no background, elegant',
    fontFamily: 'Inter',
    fontSize: 22,
    color: '#FFFFFF',
    highlightColor: '#FFFFFF',
    backgroundColor: 'transparent',
    position: 'bottom',
    verticalOffset: 8,
    textAlign: 'center',
    textTransform: 'none',
    animation: 'none',
    boxPadding: 0,
    boxRadius: 0,
    textShadow: '0 2px 10px rgba(0,0,0,0.95), 0 1px 3px rgba(0,0,0,0.8)',
    fontWeight: '600',
    letterSpacing: '-0.01em',
    strokeColor: null,
    strokeWidth: 0,
  },
  fire: {
    id: 'fire',
    name: '🔴 Fire Drop',
    description: 'Red accent on white — high contrast alert-style caption',
    fontFamily: 'Poppins',
    fontSize: 28,
    color: '#FFFFFF',
    highlightColor: '#EF4444',
    backgroundColor: 'rgba(0,0,0,0.65)',
    position: 'bottom',
    verticalOffset: 10,
    textAlign: 'center',
    textTransform: 'uppercase',
    animation: 'bounce',
    boxPadding: 10,
    boxRadius: 10,
    textShadow: '0 2px 8px rgba(0,0,0,0.95)',
    fontWeight: '800',
    letterSpacing: '0.03em',
    strokeColor: null,
    strokeWidth: 0,
  },
  cinema: {
    id: 'cinema',
    name: '🎬 Cinematic',
    description: 'Italic serif lowercase caption, bottom-center, movie style',
    fontFamily: 'Inter',
    fontSize: 20,
    color: '#F8FAFC',
    highlightColor: '#94A3B8',
    backgroundColor: 'rgba(0,0,0,0.6)',
    position: 'bottom',
    verticalOffset: 6,
    textAlign: 'center',
    textTransform: 'none',
    animation: 'fade',
    boxPadding: 10,
    boxRadius: 4,
    textShadow: 'none',
    fontWeight: '400',
    letterSpacing: '0.01em',
    strokeColor: null,
    strokeWidth: 0,
    fontStyle: 'italic',
  },
};

export const AVAILABLE_FONTS = [
  { id: 'Poppins', name: 'Poppins (Geometric Bold)' },
  { id: 'Montserrat', name: 'Montserrat (Viral Impact)' },
  { id: 'Outfit', name: 'Outfit (Modern Display)' },
  { id: 'Plus Jakarta Sans', name: 'Plus Jakarta Sans (Crisp)' },
  { id: 'Inter', name: 'Inter (Clean Neutral)' },
  { id: 'Oswald', name: 'Oswald (Condensed)' },
];

export const COLOR_PRESETS = [
  '#FFFFFF',
  '#FACC15',  // Yellow
  '#38BDF8',  // Cyan
  '#4ADE80',  // Green
  '#EF4444',  // Red
  '#F43F5E',  // Rose
  '#A855F7',  // Violet
  '#FB923C',  // Orange
  '#E2E8F0',  // Silver
];

// Default style applied to every new project
export const DEFAULT_STYLE_ID = 'tiktok';
